name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          # This MUST match the name in your GitHub Secret Vault
          HF_TOKEN: ${{ secrets.HF_SYNC_NEW }} 
        run: |
          git config --global user.email "git-sync@example.com"
          git config --global user.name "Git Sync"
          # We use the 'HF_TOKEN' variable defined above to authenticate
          git push --force https://daratharunsai:$HF_TOKEN@huggingface.co/spaces/daratharunsai/traffic-ai-engine main